---
# tasks file for mongodb

- name: Install system prerequisites including Java
  ansible.builtin.apt:
    name:
      - gnupg
      - curl
      - openjdk-21-jre-headless  # Java für Graylog
      - net-tools                # für netstat debugging
    state: present
    update_cache: yes

- name: Verify Java installation
  ansible.builtin.command:
    cmd: java -version
  register: java_version
  
- name: Display Java version
  ansible.builtin.debug:
    msg: "Java installed: {{ java_version.stderr_lines[0] }}"

- name: Add MongoDB GPG key (using shell for robustness)
  ansible.builtin.shell:
    cmd: "curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor"
  args:
    creates: /usr/share/keyrings/mongodb-server-7.0.gpg

- name: Add MongoDB repository
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse"
    state: present
    filename: mongodb-org-7.0
    update_cache: yes

- name: Install MongoDB packages
  ansible.builtin.apt:
    name: mongodb-org
    state: present

- name: Prevent MongoDB packages from being upgraded
  ansible.builtin.dpkg_selections:
    name: mongodb-org
    selection: hold

- name: Configure MongoDB
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart mongod

- name: Ensure mongod service is enabled and started
  ansible.builtin.service:
    name: mongod
    enabled: yes
    state: started

- name: Wait for MongoDB to be ready
  ansible.builtin.wait_for:
    port: 27017
    host: 127.0.0.1
    timeout: 30
