---
# tasks file for mongodb role

- name: MongoDB | Add MongoDB GPG key
  ansible.builtin.get_url:
    url: "{{ mongodb_gpg_key_url }}"
    dest: /etc/apt/trusted.gpg.d/mongodb-org-{{ mongodb_version }}.asc
    mode: '0644'
    force: yes
  become: yes
  vars:
    mongodb_gpg_key_url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"

- name: MongoDB | Add MongoDB repository
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse"
    state: present
    filename: mongodb-org-{{ mongodb_version }}
  become: yes

- name: MongoDB | Install MongoDB package
  ansible.builtin.apt:
    name: "mongodb-org={{ mongodb_package_version }}"
    state: present
    update_cache: yes
  become: yes
  notify: Start and enable mongod

- name: MongoDB | Ensure mongod service is started and enabled
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: yes
    daemon_reload: yes
  become:
yes
